### PR TITLE
`KDOC_WITHOUT_THROWS_TAG` add `@throws` annotation when throw inside try-catch

### LINKED ISSUE #1718: `KDOC_WITHOUT_THROWS_TAG` add `@throws` annotation when throw inside try catch
## Describe the bug
I sometime use `throw` inside a `try catch` when I feel like it makes sense, for example to do extra verifications on user input (see example below).

## Expected behavior
Do nothing

## Observed behavior
`KDOC_WITHOUT_THROWS_TAG` rule add a `@throws` annotation to the function, but it's wrong, this function does not throw anything as it is already caught by the surrounding try catch

## Steps to Reproduce
```
/**
 * @throws NumberFormatException
 */
fun parseInputNumber(onSuccess: (number: Int) -> Unit, onFailure: () -> Unit) {
    try {
        val input: Int = binding.inputEditText.text.toString().toInt()
        if (input < 0)
            throw NumberFormatException()

        onSuccess(input)
    } catch (e: NumberFormatException) {
        onFailure()
    }
}
```

## Environment information
* diktat version: 1.2.5
* build tool (maven/gradle): Gradle 8.2.1 & AGP 8.1.0
* how is diktat run (CLI, plugin, etc.): Plugin
* kotlin version: 1.9.0
* operating system: Ubuntu 22.04
* link to a project (if your project is public): -

### PR DESCRIPTION
**Pull request by diphtongue**
### What's done:
- Fixed `KDOC_WITHOUT_THROWS_TAG` rule when it adds a @throws annotation to the function, which has `throw` inside try-catch block

Closes #1718

### CODE REVIEW

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt [hunk 1]
```diff
@@ -61,4 +61,10 @@ class KdocMethodsFixTest : FixTestBase("test/paragraph2/kdoc/package/src/main/ko
     fun `KdocMethods rule should reformat code (full example)`() {
         fixAndCompare("KdocMethodsFullExpected.kt", "KdocMethodsFullTested.kt")
     }
+
+    @Test
+    @Tag(WarningNames.KDOC_WITHOUT_THROWS_TAG)
+    fun `@throws tag shouldn't be added`() {
```
Comment (DrAlexD) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt:67]: Add more understandable name for the test. For example, `@throws tag shouldn't be added inside try-catch`

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt [hunk 2]
```diff
@@ -197,11 +200,38 @@ class KdocMethods(configRules: List<RulesConfig>) : DiktatRule(
                 && !hasReturnKdoc && !isReferenceExpressionWithSameName
     }
 
+    private fun isThrowInTryCatchBlock(node: ASTNode?): Boolean {
+        node ?: return false
+        var parent = node.treeParent
+        while (parent != null && parent.elementType != TRY) {
+            parent = parent.treeParent
+        }
+        val nodeNameList = node.findAllDescendantsWithSpecificType(IDENTIFIER)
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt:209]: ?

```suggestion
        val nodeNameList = node.findAllDescendantsWithSpecificType(IDENTIFIER).firstOrNull()
```

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt [hunk 3]
```diff
@@ -197,11 +200,38 @@ class KdocMethods(configRules: List<RulesConfig>) : DiktatRule(
...
+        } else {
+            null
+        }
+
+        if (parent?.elementType == TRY) {
+            val catchNodes = parent.getAllChildrenWithType(CATCH)
+            val findName = catchNodes.find { catchNode ->
+                val catchNodeNames = catchNode.findAllDescendantsWithSpecificType(IDENTIFIER)
+                val matchingName = catchNodeNames.find { catchNodeName -> catchNodeName.text == nodeName?.text }
+                matchingName != null
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt:221]:
```suggestion
            val findName = parent.getAllChildrenWithType(CATCH).firstOrNull { catchNode ->
                val matchingName = catchNode.findAllDescendantsWithSpecificType(IDENTIFIER).firstOrNull { catchNodeName -> catchNodeName.text == nodeName?.text }
                }
                matchingName != null
```

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagExpected.kt [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+    try {
+        val input: Int = binding.inputEditText.text.toString().toInt()
+        if (input < 0)
+            throw NumberFormatException()
+
+        onSuccess(input)
+    } catch (e: NumberFormatException) {
+        onFailure()
+    }
+}
```
Comment (DrAlexD) [inline diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagExpected.kt:17]: I think you can use only warnings tests, no need in fix tests. Also, please add more tests. For example, for case when the thrown exception is child of exception described in catch block. Or when catch block is empty.

**Comment by kgevorkyan** [comment]
Discussed offline, lets cover with tests following cases

1) There shouldnt be any warning in:

```kotlin
try {
// ...
  throw(ex1)
// ...
} catch(ex1) {
} catch(ex2) {
} catch(ex3)
```
2) There shouldnt be any warning in:
```kotlin
try {
// ...
  throw NumberException
// ...
} catch(IlligalArgumentException) {
```
since NumberException is child of IlligalArgumentException

3) We **should** warn in this case
```kotlin
try {
// ...
  throw(ex1)
// ...
throw(ex2)

} catch(ex1) {
} catch(ex2) {
} catch(ex3)
```
`ex3` here is not catched , so we need add `@throws ex3`

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt (hunk 2 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt (hunk 3 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt]: Done

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt (hunk 1 above)
Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt]: Done

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagExpected.kt (hunk 4 above)
Comment (diphtongue) [reply diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagExpected.kt:17]: Done

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagTested.kt [hunk 5]
```diff
@@ -0,0 +1,13 @@
+package test.paragraph2.kdoc.`package`.src.main.kotlin.com.saveourtool.diktat.kdoc.methods
```
Comment (kgevorkyan) [inline diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagTested.kt:1]: I think this file should be end with `Test` and not `Tested`

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt [hunk 6]
```diff
@@ -272,6 +272,81 @@ class KdocMethodsTest : LintTestBase(::KdocMethods) {
...
+                        try {
+                            if (a < 0)
+                                throw ex1()
+                        } catch (e: ex1) {
+                            print(1)
+                        } catch (e: ex2) {
+                            print(2)
+                        } catch (e: ex3) {
+                            print(3)
+                        }
```
Comment (DrAlexD) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt:295]: Could you use real exceptions? It may be worth adding a case related to child exceptions, as in fix test.

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt [hunk 7]
```diff
@@ -197,11 +201,42 @@ class KdocMethods(configRules: List<RulesConfig>) : DiktatRule(
...
+        if (parent?.elementType == TRY) {
+            val catchNodes = parent.getAllChildrenWithType(CATCH)
+            val findName = catchNodes.firstOrNull { catchNode ->
+                val matchingName = catchNode.findAllDescendantsWithSpecificType(IDENTIFIER)
+                    .firstOrNull { catchNodeName ->
+                        nodeName.text == catchNodeName.text || try {
+                            val nodeClass = forName("java.lang.${nodeName.text}")
+                            val nodeInstance = nodeClass.getDeclaredConstructor().newInstance()
+                            val catchNodeClass = forName("java.lang.${catchNodeName.text}")
+                            catchNodeClass.isInstance(nodeInstance)
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt:221]: will you add test for this?

**Review by kgevorkyan — APPROVED** [review]

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt [hunk 8]
```diff
@@ -272,6 +272,81 @@ class KdocMethodsTest : LintTestBase(::KdocMethods) {
...
+                        try {
+                            if (a < 0)
+                                throw ex1()
+                        throw ex2()
+                        throw ex3()
+                        } catch (e: ex1) {
+                            print(1)
+                        } catch (e: ex2) {
+                            print(2)
+                        }
```
Comment (DrAlexD) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt:321]: Could you use real exceptions? It may be worth adding a case related to child exceptions, as in fix test. I also think it's worth putting this in the fix test to show the addition of `@throws` for the remaining exceptions.

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagExpected.kt [hunk 9]
```diff
@@ -0,0 +1,17 @@
...
+fun parseInputNumber(onSuccess: (number: Int) -> Unit, onFailure: () -> Unit) {
+    try {
+        val input: Int = binding.inputEditText.text.toString().toInt()
+        if (input < 0)
+            throw NumberFormatException()
+
+        onSuccess(input)
+    } catch (e: NumberFormatException) {
+        onFailure()
+    }
```
Comment (DrAlexD) [inline diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagExpected.kt:16]: I think this functionality is included in the warning tests, and it makes no sense to describe it in the fix test, because in this case there should be no warning, and thus there is no need for a fix.

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagTested.kt (hunk 5 above)
Comment (diphtongue) [reply diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagTested.kt:1]: Discussed offline

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt (hunk 6 above)
Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt]: Done

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagExpected.kt (hunk 9 above)
Comment (diphtongue) [reply diktat-rules/src/test/resources/test/paragraph2/kdoc/package/src/main/kotlin/com/saveourtool/diktat/kdoc/methods/KdocWithoutThrowsTagExpected.kt]: Done

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt (hunk 8 above)
Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt [hunk 10]
```diff
@@ -197,11 +201,42 @@ class KdocMethods(configRules: List<RulesConfig>) : DiktatRule(
                 && !hasReturnKdoc && !isReferenceExpressionWithSameName
     }
 
+    private fun isThrowInTryCatchBlock(node: ASTNode?): Boolean {
+        node ?: return false
+        var parent = node.treeParent
+        while (parent != null && parent.elementType != TRY) {
+            parent = parent.treeParent
+        }
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt:209]: As far as I remember, there is a `node.parents()` function to find all the parents of the current node.

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt [hunk 11]
```diff
@@ -197,11 +201,42 @@ class KdocMethods(configRules: List<RulesConfig>) : DiktatRule(
...
+        val nodeName = node.findAllDescendantsWithSpecificType(IDENTIFIER).firstOrNull() ?: return false
+
+        if (parent?.elementType == TRY) {
+            val catchNodes = parent.getAllChildrenWithType(CATCH)
+            val findNodeWithMatchingName = catchNodes.firstOrNull { catchNode ->
+                val matchingNameForCatchNode = catchNode.findAllDescendantsWithSpecificType(IDENTIFIER)
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt:215]: Maybe it's worth changing names of variables to take into account new logic that takes into account child elements of exceptions, and not just matching of their names?

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt [hunk 12]
```diff
@@ -272,6 +272,81 @@ class KdocMethodsTest : LintTestBase(::KdocMethods) {
         )
     }
 
+    @Test
+    @Tag(WarningNames.KDOC_WITHOUT_THROWS_TAG)
+    fun `No warning when catch without matching throw`() {
```
Comment (DrAlexD) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt:277]: What does this test name mean?

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt [hunk 13]
```diff
@@ -61,4 +61,10 @@ class KdocMethodsFixTest : FixTestBase("test/paragraph2/kdoc/package/src/main/ko
     fun `KdocMethods rule should reformat code (full example)`() {
         fixAndCompare("KdocMethodsFullExpected.kt", "KdocMethodsFullTested.kt")
     }
+
+    @Test
+    @Tag(WarningNames.KDOC_WITHOUT_THROWS_TAG)
+    fun `@throws tag shouldn't be added inside try-catch`() {
+        fixAndCompare("KdocWithoutThrowsTagExpected.kt", "KdocWithoutThrowsTagTested.kt")
```
Comment (DrAlexD) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt:68]: In the current logic of these tests, this is a mistake name.

Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt:68]: Does this name `Should add throws tag only for throw without catch` fit?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt (hunk 10 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt (hunk 11 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocMethods.kt]: Done

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt (hunk 12 above)
Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsTest.kt]: Changed: `No warning when throw has matching catch`

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt (hunk 13 above)
Comment (DrAlexD) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter2/KdocMethodsFixTest.kt]: Yes, its ok
