### PR TITLE
Fixed WRONG_MULTIPLE_MODIFIERS_ORDER bug in SAM interface

### LINKED ISSUE #1598: WRONG_MULTIPLE_MODIFIERS_ORDER triggers on SAM interface
## Describe the bug

Having the following valid code snippet:
```kotlin
public fun interface Factory {
    public fun create(): List<Int>
}
```

Diktat fails with the error:
```
[WRONG_MULTIPLE_MODIFIERS_ORDER] sequence of modifier-keywords is incorrect: public should be on position 2, but is on position 1 (diktat-ruleset:multiple-modifiers)
[WRONG_MULTIPLE_MODIFIERS_ORDER] sequence of modifier-keywords is incorrect: fun should be on position 1, but is on position 2 (diktat-ruleset:multiple-modifiers
```

## Expected behavior
`public fun interface` should not trigger this rule

## Environment information
* diktat version: diktat-1.2.4.2.jar
* how is diktat run (CLI, plugin, etc.): CLI
* kotlin version: 1.8.0

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* fixed WRONG_MULTIPLE_MODIFIERS_ORDER bug in SAM interface

Closes #1598

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MultipleModifiersSequence.kt [hunk 1]
```diff
@@ -46,6 +51,15 @@ class MultipleModifiersSequence(configRules: List<RulesConfig>) : DiktatRule(
         }
     }
 
+    private fun isSamInterfaces(parent: ASTNode, node: ASTNode): Boolean {
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MultipleModifiersSequence.kt:54]: I think we also need to check, that this interface contains only one abstract method, isn't it?

Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MultipleModifiersSequence.kt:54]: I think that for this we need to make a separate rule, this no longer concerns the logic of the order of modifiers.

Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MultipleModifiersSequence.kt:54]: Fixed

**Review by kgevorkyan — APPROVED** [review]

**Review by nulls — APPROVED** [review]
