### PR TITLE
Use ktlint's mechanism to initialize loggers

### LINKED ISSUE #1413: Unexpected debug logs in 1.2.0
## Describe the bug

I'm using gradle plugin with the following setup:
```
plugins {
    id("org.cqfn.diktat.diktat-gradle-plugin").version("1.2.0")
}

diktat {
    inputs {
        it.include("src/**/*.kt")
    }
}
```

Note that downgrading to 1.1.0 solves the issue

## Expected behavior

I expect to see only issues related strings in the output

## Observed behavior

I also see dozens of lines like this ones - looks like the count depends on processing files count:
```
09:32:05.102 [main] DEBUG org.cqfn.diktat.ruleset.rules.DiktatRuleSetProvider - Will run diktat-ruleset with diktat-analysis.yml (it can be placed to the run directory or the default file from resources will be used)
09:32:05.102 [main] DEBUG org.cqfn.diktat.common.config.rules.RulesConfigReader - Using diktat-analysis.yml file from the following path: .../diktat-analysis.yml
09:32:05.384 [Thread-0] DEBUG org.cqfn.diktat.ruleset.rules.DiktatRuleSetProvider - Will run diktat-ruleset with diktat-analysis.yml (it can be placed to the run directory or the default file from resources will be used)
09:32:05.385 [Thread-0] DEBUG org.cqfn.diktat.common.config.rules.RulesConfigReader - Using diktat-analysis.yml file from the following path: .../diktat-analysis.yml
```

## Steps to Reproduce

1. Open [attached sample project](https://github.com/saveourtool/diktat/files/9006798/MyApplication.zip)
2. run `./gradlew diktatCheck`

## Environment information
* diktat version: 1.2.0
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): plugin
* kotlin version: 1.7.0
* operating system: MacOS

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Initialize loggers using kotlin-logging and extension from ktlint-core

This pull request closes #1413. Full description of the problem is in #1394

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt [hunk 1]
```diff
@@ -25,7 +27,9 @@ import java.util.function.Consumer
 internal const val TEST_FILE_NAME = "TestFileName.kt"
 
 @Suppress("WRONG_WHITESPACE")
-private val log = LoggerFactory.getLogger({}.javaClass)
+private val log = KotlinLogging.logger(
```
Comment (nulls) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt:30]: suggestion create an extension function for KotlinLogging which applies .initKtLintKLogger()

Also, why we do not use the following way of initialization: `KotlinLogging.logger {}.initKtLintKLogger()`?

**Comment by nulls** [comment]
this problem is relevant for gradle plugin (because we run ktlint as `java -jar`), but what's about maven plugin where we call ktlint directly? 
Do we support different log level for maven plugin?

**Review by nulls — APPROVED** [review]

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt:30]: Funny thing - diktat complains on such expressions because of an empty block. I don't want to place a lot of new suppresses, we should maybe thing of some other way to allow these

**Comment by nulls** [comment]
> In maven plugin we don't depend on ktlint-cli and therefore don't depend on `logback`.

There aren't logging in ktlint\diktat code which is called by maven plugin, are there?

**Comment by petertrr** [comment]
> > In maven plugin we don't depend on ktlint-cli and therefore don't depend on `logback`.
> 
> There aren't logging in ktlint\diktat code which is called by maven plugin, are there?

We are using a logger returned by `AbstractMojo#getLog()`, and it's slf4j-compatible AFIU
