### PR TITLE
Fixed warning `FUNCTION_BOOLEAN_PREFIX` on `operator fun`

### LINKED ISSUE #1723: `FUNCTION_BOOLEAN_PREFIX` on `operator fun`
Diktat should not treat this code as an error

```Kotlin
inline operator fun component3(): Boolean = asDynamic()[2].unsafeCast<Boolean>()
```

while this error message is shown:

    [FUNCTION_BOOLEAN_PREFIX] functions that return the value of Boolean type should have <is> or <has> prefix: component3 (diktat-ruleset:identifier-naming)

### PR DESCRIPTION
**Pull request by diphtongue**
### What's done:
- fixed warning `FUNCTION_BOOLEAN_PREFIX` on `operator fun`.
- added warning test.

Closes #1723

### CODE REVIEW

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 1]
```diff
@@ -412,7 +412,9 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
             @Suppress("COLLAPSE_IF_STATEMENTS")
             if (functionReturnType != null && functionReturnType == PrimitiveType.BOOLEAN.typeName.asString()) {
                 @Suppress("COLLAPSE_IF_STATEMENTS")
-                if (allMethodPrefixes.none { functionName.text.startsWith(it) }) {
+                val isOperatorFun = node.firstChildNode?.findChildrenMatching { it.elementType == KtNodeTypes.OPERATION_REFERENCE }
```
Comment (sanyavertolet) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:415]: I'd move this to a separate extension function of `ASTNode` and put the function invocation into the higher `if` so that it would become 
```kotlin
if(node.hasBooleanReturnType() && !node.isOperatorFun()) { ... }
```

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt [hunk 2]
```diff
@@ -183,6 +184,22 @@ fun ASTNode.isAnonymousFunction(): Boolean {
     return this.getIdentifierName() == null
 }
 
+/**
+ * Checks if the function has boolean return type
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt:188]: please add kdoc `@return`

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt [hunk 3]
```diff
@@ -183,6 +184,22 @@ fun ASTNode.isAnonymousFunction(): Boolean {
...
+ */
+fun ASTNode.hasBooleanReturnType(): Boolean {
+    val functionReturnType = this.findChildAfter(VALUE_PARAMETER_LIST, KtNodeTypes.TYPE_REFERENCE)?.text
+    return functionReturnType != null && functionReturnType == PrimitiveType.BOOLEAN.typeName.asString()
+}
+
+/**
+ * Checks if the function is an operator function
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt:196]: please add kdoc `@return`

**Review by nulls — APPROVED** [review]

**Review by DrAlexD — APPROVED** [review]

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt (hunk 2 above)
Comment (kgevorkyan) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt:188]: why diktat didnt require it by itself?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt (hunk 3 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt:197]: Done.

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt (hunk 2 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt:188]: Done. There was a `KDOC_WITHOUT_RETURN_TAG` suppress.

Comment (nulls) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt:188]: discussed offline: `AstNodeUtils.kt` has suppression for this rule on whole file.

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt [hunk 4]
```diff
@@ -7,7 +7,7 @@
     "FILE_NAME_MATCH_CLASS",
     "KDOC_WITHOUT_RETURN_TAG",
     "KDOC_WITHOUT_PARAM_TAG",
-    "MatchingDeclarationName",
+    "MatchingDeclarationName"
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt:10]: better to leave a comma at the end. it will avoid change in this line in case of adding a new element at the end

**Review by nulls — APPROVED** [review]

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt (hunk 4 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/utils/AstNodeUtils.kt]: Done.
