### PR TITLE
Properly format expressions wrapped *before* a binary operator

### LINKED ISSUE #1340: `WRONG_INDENTATION`: `extendedIndentAfterOperators` ignored if lines are wrapped before a binary operator or an infix function
Consider this fragment (originally from https://github.com/saveourtool/diktat/issues/1312#issuecomment-1140119752)

```kotlin
systemUiVisibility = (View.SYSTEM_UI_FLAG_LOW_PROFILE
        or View.SYSTEM_UI_FLAG_FULLSCREEN
        or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
        or View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
        or View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
        or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION)
```

Here, infix function calls are wrapped _before_ the operator (the infix function), and `extendedIndentAfterOperators` has no effect (DiKTat always expects a _single_ indent, not a _continuation_ indent).

The workaround (fir version 1.1.0) is to reformat the code as follows (https://github.com/saveourtool/diktat/issues/1312#issuecomment-1142337550):

```kotlin
systemUiVisibility = (View.SYSTEM_UI_FLAG_LOW_PROFILE or
        View.SYSTEM_UI_FLAG_FULLSCREEN or
        View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
        View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY or
        View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or
        View.SYSTEM_UI_FLAG_HIDE_NAVIGATION)
```

The expected behaviour is that `extendedIndentAfterOperators` is honored regardless of whether the code is wrapped _before_ or _after_ a binary operator.

Other examples (the code style assumes `extendedIndentAfterOperators` is **on**):

```kotlin
const val FOO = 1

const val BAR = 2

const val BAZ = 4

fun acceptInteger(arg: Int) = Unit

fun main() {
    acceptInteger(FOO or BAR or BAZ or FOO or BAR or BAZ
            or FOO or BAR or BAZ or FOO or BAR or BAZ or FOO or BAR or BAZ
            or FOO or BAR or BAZ)
}
```

```kotlin
const val TRUE = true

const val FALSE = false

fun acceptBoolean(arg: Boolean) = Unit

fun main() {
    acceptBoolean(TRUE
            || FALSE
            || TRUE)
}
```

```kotlin
val c = (3
        + 2)
```

```kotlin
infix fun Int.combineWith(that: Int) = this + that

fun main() {
    val x = (1
            combineWith 2
            combineWith 3
            combineWith 4
            combineWith 5
            combineWith 6)
}
```

# `when`- and `for`-statements

The argument of a `when`-expression:

```kotlin
when (true
        || false) {
    true -> Unit
    else -> Unit
}
```

The branch condition of a `when`-expression:

```kotlin
when ("".isEmpty()) {
    (true
            || false) -> Unit
    else -> Unit
}
```

Infix function calls in a `for`-loop:

```kotlin
for (i in 6
        downTo 0
        step 2) {
    return
}
```

Operator function calls in a `for`-loop:

```kotlin
for (i in 1
        ..42) {
    return
}
```

# More examples

```kotlin
true
        || false

val a = true
        || false
```

# Expressions wrapped in parentheses

Affected by the fix for #1409, see [this comment](https://github.com/saveourtool/diktat/issues/1340#issuecomment-1170026704).

```kotlin
(true
        || false)

val a = (true
        || false)
```

# `if`-conditions (should be controlled by a separate flag)

A slightly modified example from IDEA code style settings (`CONTINUATION_INDENT_IN_IF_CONDITIONS` is **on**):

```kotlin
fun foo1(i1: Int, i2: Int, i3: Int): Int {
    if (i2 > 0
            && i3 < 0) {
        return 2
    }
    return 0
}
```

Minimal repro:

```kotlin
if (true
        || false) {
    return
}
```

or 

```kotlin
while (true
        || false) {
    return
}
```
## Environment information
* diktat version: 1.1.0
* build tool (maven/gradle): _Maven_
* how is diktat run (CLI, plugin, etc.): `mvn diktat:check`
* kotlin version: **1.6.21**
* operating system: Windows 10

### PR DESCRIPTION
**Pull request by 0x6675636b796f75676974687562**
### What's done:

 * Now, the indentation in binary expressions wrapped *before* a binary operator
   or an infix function is also controlled with `extendedIndentAfterOperators`.
 * The above is also true for `as` and `as?` operators.
 * The only exclusion is the Elvis operator (`?:`).
 * Fixes #1340.

### CODE REVIEW

**Review by akuleshov7 — APPROVED** [review]

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestResources.kt [hunk 1]
```diff
@@ -605,6 +605,29 @@ internal object IndentationRuleTestResources {
         |            2 to
         |            3))
         """.trimMargin(),
+
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleTestResources.kt:608]: Actually - I suggest to split resources - we don't need to have huge unit tests that have complex logic (especially when warnings are far away from the code)

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleWarnTest.kt [hunk 2]
```diff
@@ -909,6 +910,48 @@ class IndentationRuleWarnTest : LintTestBase(::IndentationRule) {
...
+        fun `should be reported if mis-indented`(extendedIndentAfterOperators: Boolean) {
+            val defaultConfig = IndentationConfig(NEWLINE_AT_END to false)
+            val customConfig = defaultConfig.withCustomParameters(EXTENDED_INDENT_AFTER_OPERATORS to extendedIndentAfterOperators)
+
+            assertSoftly { softly ->
+                expressionsWrappedBeforeOperator[!extendedIndentAfterOperators].assertNotNull().forEach { code ->
+                    softly.assertThat(lintResult(code, customConfig.asRulesConfigList()))
+                        .describedAs("lint result for ${code.describe()}")
+                        .isNotEmpty
+                        .hasSizeBetween(1, 5).allSatisfy(Consumer { lintError ->
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/IndentationRuleWarnTest.kt:945]: expecting from 1 to 5 warnings :)
