### PR TITLE
Fixed false positive findings [PARAMETER_NAME_IN_OUTER_LAMBDA] 

### LINKED ISSUE #1880: [PARAMETER_NAME_IN_OUTER_LAMBDA] False positive findings
## Describe the bug

False positive findings when lambda operation at the same level:
```kotlin
@Suppress("PARAMETER_NAME_IN_OUTER_LAMBDA")
overrideFunctions.forEach {
    functionNameMap.compute(it.getIdentifierName()!!.text) { _, oldValue -> (oldValue ?: 0) + 1 }
}
```

```kotlin
    private fun isCheckNeeded(whiteSpace: PsiWhiteSpace) =
        whiteSpace.parent
            .node
            .elementType
            .let { it == VALUE_PARAMETER_LIST || it == VALUE_ARGUMENT_LIST } &&
                whiteSpace.siblings(forward = false, withItself = false).none { it is PsiWhiteSpace && it.textContains('\n') } &&
                @Suppress("PARAMETER_NAME_IN_OUTER_LAMBDA")
                // no need to trigger when there are no more parameters in the list
                whiteSpace.siblings(forward = true, withItself = false).any {
                    it.node.elementType.run { this == VALUE_ARGUMENT || this == VALUE_PARAMETER }
                }
```

```kotlin
    @Suppress("PARAMETER_NAME_IN_OUTER_LAMBDA")
    private fun checkBlankLineAfterKdoc(node: ASTNode) {
        commentType.forEach {
            val kdoc = node.getFirstChildWithType(it)
            kdoc?.treeNext?.let { nodeAfterKdoc ->
                if (nodeAfterKdoc.elementType == WHITE_SPACE && nodeAfterKdoc.numNewLines() > 1) {
                    WRONG_NEWLINES_AROUND_KDOC.warnAndFix(configRules, emitWarn, isFixMode, "redundant blank line after ${kdoc.text}", nodeAfterKdoc.startOffset, nodeAfterKdoc) {
                        nodeAfterKdoc.leaveOnlyOneNewLine()
                    }
                }
            }
        }
    }
```

```kotlin
        private fun KSAnnotation.getArgumentValue(argumentName: String): String = arguments
            .singleOrNull { it.name?.asString() == argumentName }
            .let {
                requireNotNull(it) {
                    "Not found $argumentName in $this"
                }
            }
            .value
            ?.let { it as? String }
            .let {
                requireNotNull(it) {
                    "Not found a value for $argumentName in $this"
                }
            }
```

## Expected behavior
Do not trigger when inner lambda has no `it` in the code

## Observed behavior
Remove suppressing in diktat

## Environment information
* diktat version: 2.0.0
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): plugin
* kotlin version: 1.9.21
* operating system: Windows
* link to a project (if your project is public): diktat

### PR DESCRIPTION
**Pull request by diphtongue**
### What's done:
- Fixed false positive findings when lambda operation at the same level
- Added warn tests

Closes #1880

### CODE REVIEW

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt [hunk 1]
```diff
@@ -35,7 +43,16 @@ class ParameterNameInOuterLambdaRule(configRules: List<RulesConfig>) : DiktatRul
             )
         }
     }
+
     companion object {
         const val NAME_ID = "parameter-name-in-outer-lambda"
     }
+
+    @Suppress("MISSING_KDOC_CLASS_ELEMENTS")
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt:51]: Why do we suppress kdoc?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt [hunk 2]
```diff
@@ -35,7 +43,16 @@ class ParameterNameInOuterLambdaRule(configRules: List<RulesConfig>) : DiktatRul
...
+    class ParameterNameInOuterLambdaConfiguration(config: Map<String, String>) : RuleConfiguration(config) {
+        /**
+         * Flag (when false) which allows to use `it` in outer lambda, if in inner lambdas would be no `it`
+         */
+        val strictMode = (config["strictMode"] == "true")
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt:56]: Maybe should make more understandable name for configuration?

Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt:56]: Do we really need separate configuration for this?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt (hunk 1 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt]: Changed

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt [hunk 3]
```diff
@@ -24,9 +29,19 @@ class ParameterNameInOuterLambdaRule(configRules: List<RulesConfig>) : DiktatRul
     }
 
     private fun checkLambda(node: ASTNode) {
-        val hasInnerLambda = node
-            .findAllDescendantsWithSpecificType(KtNodeTypes.LAMBDA_EXPRESSION, false)
-            .isNotEmpty()
+        val configuration = ParameterNameInOuterLambdaConfiguration(
+            configRules.getRuleConfig(PARAMETER_NAME_IN_OUTER_LAMBDA)?.configuration
+                ?: emptyMap()
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt:34]: Maybe it's better to extract this from method?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt [hunk 4]
```diff
@@ -24,9 +29,19 @@ class ParameterNameInOuterLambdaRule(configRules: List<RulesConfig>) : DiktatRul
...
+        )
+        val strictMode = configuration.strictMode
+
+        val innerLambdaList = node.findAllDescendantsWithSpecificType(KtNodeTypes.LAMBDA_EXPRESSION, false)
+        val hasInnerLambda = innerLambdaList.isNotEmpty()
+
+        if (!strictMode && (hasNoParameters(node) || node.hasExplicitIt()) && (!hasInnerLambda ||
+                innerLambdaList.all { innerLambda -> !hasItInLambda(innerLambda) })) {
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt:42]: Maybe it would be better to extract this condition into variable or method and give it clearer name?

File: diktat-rules/src/main/resources/diktat-analysis.yml [hunk 5]
```diff
@@ -455,6 +455,8 @@
 # Check that lambda with inner lambda doesn't use implicit parameter
 - name: PARAMETER_NAME_IN_OUTER_LAMBDA
   enabled: true
+  configuration:
+    strictMode: true # don't let outer lambdas have `it` as parameter
```
Comment (DrAlexD) [inline diktat-rules/src/main/resources/diktat-analysis.yml:459]: Add configuration to the other `diktat-analysis.yml` files as well

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt [hunk 6]
```diff
@@ -35,6 +50,19 @@ class ParameterNameInOuterLambdaRule(configRules: List<RulesConfig>) : DiktatRul
...
+    /**
+     * ParameterNameInOuterLambdaConfiguration used when we need to allow the usage of 'it' in outer lambda
+     *
+     * @param config - map of strings with configuration options for a Parameter Name In Outer Lambda rule
+     */
+    class ParameterNameInOuterLambdaConfiguration(config: Map<String, String>) : RuleConfiguration(config) {
+        /**
+         * Flag (when false) allows to use `it` in outer lambda, if in inner lambdas would be no `it`
+         */
+        val strictMode = (config["strictMode"] == "true")
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt:63]: Maybe it would be better to change it to `config["strictMode"]?.toBoolean() ?: true` or `config["strictMode"]?.toBoolean() ?: false` to be able to specify default value?

Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt]: Done

File: diktat-rules/src/main/resources/diktat-analysis.yml (hunk 5 above)
Comment (diphtongue) [reply diktat-rules/src/main/resources/diktat-analysis.yml:459]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt (hunk 4 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt (hunk 3 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt [hunk 7]
```diff
@@ -17,16 +22,35 @@ class ParameterNameInOuterLambdaRule(configRules: List<RulesConfig>) : DiktatRul
     configRules,
     listOf(PARAMETER_NAME_IN_OUTER_LAMBDA)
 ) {
+    /**
+     * Configuration for the rule ParameterNameInOuterLambda
+     */
+    val configuration by lazy {
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt:28]: can be private

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt [hunk 8]
```diff
@@ -17,16 +22,35 @@ class ParameterNameInOuterLambdaRule(configRules: List<RulesConfig>) : DiktatRul
...
         if (node.elementType == KtNodeTypes.LAMBDA_EXPRESSION) {
             checkLambda(node)
         }
     }
 
     private fun checkLambda(node: ASTNode) {
-        val hasInnerLambda = node
-            .findAllDescendantsWithSpecificType(KtNodeTypes.LAMBDA_EXPRESSION, false)
-            .isNotEmpty()
+        val configuration: ParameterNameInOuterLambdaConfiguration = configuration
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt:41]: why we need it?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt (hunk 7 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt (hunk 8 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter5/ParameterNameInOuterLambdaRule.kt]: Deleted

**Review by nulls — APPROVED** [review]
