### PR TITLE
Don't change the indent for parentheses-enclosed expressions

### LINKED ISSUE #1409: `WRONG_INDENTATION`: false positives for parentheses-surrounded infix expressions
The following code fragment triggers no errors, provided that `expectedIndentAfterOperators` is **off**:

```kotlin
val value = 1 to
    2
```

Now, let's surround the expression (which is an infix function call) with parentheses, preserving the indent:

```kotlin
val value = (1 to
    2)
```

_DiKTat_ will report the following errors:

```
[WRONG_INDENTATION] only spaces are allowed for indentation and each indentation should equal to 4 spaces (tabs are not allowed): expected 8 but was 4
[WRONG_INDENTATION] only spaces are allowed for indentation and each indentation should equal to 4 spaces (tabs are not allowed): expected 8 but was 4
```

Strangely, if we move the expression onto the next line (and increment the indent), the errors immediately go away:

```kotlin
val value =
    (1 to
        2)
```

## Environment information
* diktat version: 1.2.0
* build tool (maven/gradle): Maven
* how is diktat run (CLI, plugin, etc.): Maven plug-in
* kotlin version: 1.7.0
* operating system: Windows

### PR DESCRIPTION
**Pull request by 0x6675636b796f75676974687562**
### What's done:

 * From now on, parentheses (`LPAR`/`RPAR`) don't increment or decrement the
   indent unless they're a part of a function declaration or a function call.
 * Parentheses which just enclose an expression don't affect the indent at all.
 * This fixes #1409.

## Actions checklist
* [X] Added tests on checks
* [X] Added tests on fixers

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationRule.kt [hunk 1]
```diff
@@ -560,6 +574,60 @@ class IndentationRule(configRules: List<RulesConfig>) : DiktatRule(
...
+         * @see PARENTHESIZED
+         * @see VALUE_ARGUMENT_LIST
+         * @see VALUE_PARAMETER_LIST
+         */
+        private fun ASTNode.isParenthesisAffectingIndent(): Boolean {
+            require(elementType in arrayOf(LPAR, RPAR)) {
+                elementType.toString()
+            }
+
+            return treeParent.elementType != PARENTHESIZED
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationRule.kt:628]: How will we handle this case:
```kotlin
fun f() = (
    1 + 2
)
```
I think, `(1+2)` is a `PARENTHESIZED` node here, but we need to increase indent after `LPAR`

Comment (0x6675636b796f75676974687562) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationRule.kt:628]: You're right indeed, thanks.

I've added unit tests (a88d8ea6181daf16946a74a933e1a85a579ed5dd) to cover this case, will fix them soon.

Comment (0x6675636b796f75676974687562) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationRule.kt]: Fixed with a848a3e8eb479827de62c668818864c507facc10.

**Review by petertrr — APPROVED** [review]
