### PR TITLE
Supertypes should be on separate lines

### LINKED ISSUE #1890: False positive with implementing several interfaces
## Describe the bug
When implementing several interfaces and executing diktat fix, for some reason the interfaces end up on new line.
## Expected behavior
```kotlin
class A<K : Any, P : Any, G : Any> : B<K>(), C<P>, D<G> {}
```
## Observed behavior
```kotlin
class A<K : Any, P : Any, G : Any> : B<K>(),
C<P>,
D<G> {}
```
## Steps to Reproduce
```kotlin
class A<K : Any, P : Any, G : Any> : B<K>(), C<P>, D<G> {}
```

### PR DESCRIPTION
**Pull request by diphtongue**
### What's done:
- Fixed bug where more than two supertypes should be on separate lines
- Added warning and smoke tests

Closes #1890

### CODE REVIEW

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/SuperClassListWarnTest.kt [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+    private val ruleId = "$DIKTAT_RULE_SET_ID:${NewlinesRule.NAME_ID}"
+
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `superclass list on the same line`() {
+        lintMethod(
+            """
+                    |package com.saveourtool.diktat
+                    |
+                    |class A<K : Any, P : Any, G : Any> : B<K>(), C<P>, D<G> {}
```
Comment (kgevorkyan) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/SuperClassListWarnTest.kt:24]: please also add test for
```kotlin
class A<K : Any, P : Any, G : Any> : B<K>(),
C<P>,
D<G> {}
```

Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/SuperClassListWarnTest.kt:24]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 2]
```diff
@@ -491,35 +494,98 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
...
+                areElementsCorrect = false
+                break
+            }
+            valueParameter = superClassType?.treeNext
+        }
+        return newlineBeforeSuperTypeList != null && areElementsCorrect
+    }
+
+    @Suppress("TOO_LONG_FUNCTION", "ComplexMethod")
+    private fun handleValueParameterList(node: ASTNode, entryType: String) {
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:527]: Maybe extract smaller functions from this large function?

Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:527]: What does value parameter list mean?

File: diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt [hunk 3]
```diff
@@ -378,6 +379,13 @@ abstract class DiktatSmokeTestBase {
         fixAndCompare(prepareOverriddenRulesConfig(), "SemicolonsExpected.kt", "SemicolonsTest.kt")
     }
 
+    @Test
+    @Tag("DiktatRuleSetProvider")
+    @Timeout(TEST_TIMEOUT_SECONDS, unit = SECONDS)
+    fun `should add newlines between interfaces`() {
+        fixAndCompare(prepareOverriddenRulesConfig(), "NewlinesAfterInterfacesExpected.kt", "NewlinesAfterInterfacesTest.kt")
+    }
+
```
Comment (DrAlexD) [inline diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt:388]: Why do we need this smoke test?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 4]
```diff
@@ -491,35 +494,98 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
...
 
-    private fun handleValueParameterList(node: ASTNode, entryType: String) = node
-        .children()
-        .filter {
-            val isNewLineNext = it.treeNext?.isNewLineNode() ?: false
-            val isNewLinePrev = it.treePrev?.isNewLineNode() ?: false
-            (it.elementType == COMMA && !isNewLineNext) ||
-                    // Move RPAR to the new line
-                    (it.elementType == RPAR && it.treePrev?.elementType != COMMA && !isNewLinePrev)
+    private fun isCorrectSuperTypeList(valueParameterList: List<ASTNode>): Boolean {
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:497]: please add kdoc, where you describe about what is **correct** supertype list

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/SuperClassListWarnTest.kt [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+                    |B<K>(),
+                    |C<P>,
+                    |D<G> {}
+            """.trimMargin(),
+        )
+    }
+
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `superclass list different white spaces`() {
```
Comment (DrAlexD) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/SuperClassListWarnTest.kt:74]: What does this name mean? Why does the name contain `white spaces`?

File: diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt (hunk 3 above)
Comment (DrAlexD) [reply diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt:388]: Maybe add fix test instead of smoke test?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 6]
```diff
@@ -491,35 +494,98 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
...
+
+        val classDefinitionNode = valueParameterList[0].treeParent?.treeParent
+        val colonNodes = classDefinitionNode?.getAllChildrenWithType(COLON)
+        val newlineBeforeSuperTypeList = colonNodes?.find {colonNode ->
+            val newlineNode = colonNode.treeNext
+            val superClassType = newlineNode?.treeNext
+            newlineNode?.text?.count { it == '\n' } == 1 && superClassType?.elementType == SUPER_TYPE_LIST
+        }
+
+        var areElementsCorrect = true
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:511]: please add comment about this, in which case are they correct

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 7]
```diff
@@ -491,35 +494,98 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
...
+    @Suppress("TOO_LONG_FUNCTION", "ComplexMethod")
+    private fun handleValueParameterList(node: ASTNode, entryType: String) {
+        val valueParameterList = node.children().toList()
+        val warnText = node.getParentIdentifier()?.let {
+            "$entryType should be placed on different lines in declaration of <${node.getParentIdentifier()}>"
+        } ?: "$entryType should be placed on different lines"
+        val classDefinitionNode = valueParameterList[0].treeParent?.treeParent
+        val colonNodes = classDefinitionNode?.getAllChildrenWithType(COLON)
+
+        if (!isCorrectSuperTypeList(valueParameterList)) {
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:535]: let extract if and else branches into separate methods

Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:535]: let extract if and else branches into separate methods

Comment (kgevorkyan) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:535]: and document them

Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:602]: Done

Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:602]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 4 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:503]: Done

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/SuperClassListWarnTest.kt (hunk 5 above)
Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter3/SuperClassListWarnTest.kt]: It means that different whitespaces doesn't effect on the result, where each superclass is on separate line

File: diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt (hunk 3 above)
Comment (diphtongue) [reply diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt:388]: Added fix test

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 2 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:594]: Value parameter list - list of supertypes and interfaces, from which our class is inherited

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 8]
```diff
@@ -491,35 +495,116 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
...
+        WRONG_NEWLINES.warnAndFix(
+            configRules, emitWarn, isFixMode,
+            warnText, node.startOffset, node
+        ) {
+            valueParameterList.forEach { superClassNode ->
+                val commaNode = superClassNode.treeNext
+                val whiteSpaceNode = commaNode?.treeNext
+                // put super classes on separate lines
+                if (superClassNode.elementType in listOf(SUPER_TYPE_CALL_ENTRY, SUPER_TYPE_ENTRY) &&
+                        commaNode != null && whiteSpaceNode?.elementType == WHITE_SPACE
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:548]: should we also check, that `comaNode.text == ","`?

**Review by kgevorkyan — APPROVED** [review]

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 8 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt]: Done

File: diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt (hunk 3 above)
Comment (DrAlexD) [inline diktat-cli/src/test/kotlin/com/saveourtool/diktat/smoke/DiktatSmokeTestBase.kt:388]: Why did you decide not to delete this smoke test?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 9]
```diff
@@ -491,35 +495,116 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
...
+                break
+            }
+            valueParameter = superClassType?.treeNext
+        }
+        return newlineBeforeSuperTypeList != null && areElementsCorrect
+    }
+
+    private fun setSuperClassesOnSeparateLines(
+        node: ASTNode,
+        valueParameterList: List<ASTNode>,
```
Comment (DrAlexD) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:535]: Change to `superTypeList`?

File: diktat-rules/src/test/resources/test/paragraph3/newlines/ParameterListTest.kt [hunk 10]
```diff
@@ -12,4 +12,4 @@ class Foo(val arg1: Int, arg2: Int, arg3: Int) {
 
 class Foo(val arg1: Int,
           var arg2: Int,
-          arg3: Int) { }
\ No newline at end of file
+          arg3: Int) { }
```
Comment (DrAlexD) [inline diktat-rules/src/test/resources/test/paragraph3/newlines/ParameterListTest.kt:15]: What has changed?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 11]
```diff
@@ -491,35 +495,116 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
...
+                            } ?: commaOrRpar.treeNext?.treeParent?.appendNewlineMergingWhiteSpace(nextWhiteSpace, commaOrRpar.treeNext)
+                        } else {
+                            commaOrRpar.treeParent?.appendNewlineMergingWhiteSpace(nextWhiteSpace, commaOrRpar)
+                        }
                     }
                 }
             }
+    }
+
+    private fun handleValueParameterList(node: ASTNode, entryType: String) {
```
[the remark this answers is not in the document]
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:594]: Discussed offline, no need.

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 9 above)
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:535]: Discussed offline, no need.

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 12]
```diff
@@ -491,35 +495,116 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
...
-            val isNewLinePrev = it.treePrev?.isNewLineNode() ?: false
-            (it.elementType == COMMA && !isNewLineNext) ||
-                    // Move RPAR to the new line
-                    (it.elementType == RPAR && it.treePrev?.elementType != COMMA && !isNewLinePrev)
+    /**
+     * Check that super classes are on separate lines (if there are three or more)
+     *
+     * @return true if there are less than three super classes or if all of them are on separate lines
+     */
+    private fun isCorrectSuperTypeList(valueParameterList: List<ASTNode>): Boolean {
```
[the remark this answers is not in the document]
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:503]: Discussed offline, no need.

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 11 above)
[the remark this answers is not in the document]
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:594]: Discussed offline

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 9 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:535]: Discussed offline

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 12 above)
[the remark this answers is not in the document]
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:503]: Discussed offline

**Review by akuleshov7 — APPROVED** [review]
