### PR TITLE
Fixed bug related to assigning to declared vals inside null-check branches

### LINKED ISSUE #1844: false positive when assigning to a declared val with a branch null check
## Describe the bug

False positive in class `init` block when assigning to a declared `val` with a branch null check.

## Expected behavior

Diktat does not rewrite the following code:

```kotlin
class Demo {
  val one: Int
  val two: String

  init {
    val number = get()
    if (number != null) {
      one = number.toInt()
      two = number
    } else {
      one = 0
      two = "0"
    }
  }

  private fun get(): String? = if (Math.random() > 0.5) { "1" } else { null }
}
```

## Observed behavior

Diktat rewrites the init block to
```kotlin
val number = get()
number?.let {
  one = number.toInt()
  two = number
} ?: run {
  one = 0
  two = "0"
}
```
which does not compile as the kotlin compiler complains that "val cannot be reassigned" (even though we can see that it wouldn't be in this case)

## Steps to Reproduce

Assign to a declared val in both branches of a null check

## Environment information
* diktat version: 1.2.5
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): spotless (spotlessApply task)
* kotlin version: 1.9.20
* operating system: macOS
* link to a project (if your project is public): NA

### PR DESCRIPTION
**Pull request by DrAlexD**
### What's done:
- Fixed bug related to case when `if-else` block inside `init` or `run`, `with`, `apply` blocks and there is more than one statement inside `else` block. This case leads to kotlin compilation error after adding `run` block instead of `else` block. Read https://youtrack.jetbrains.com/issue/KT-64174 for more information.
- Added new warning tests.

Closes #1844

### CODE REVIEW

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt [hunk 1]
```diff
@@ -72,32 +77,59 @@ class NullChecksRule(configRules: List<RulesConfig>) : DiktatRule(
...
-                    KtTokens.EQEQ, KtTokens.EQEQEQ ->
-                        warnAndFixOnNullCheck(
-                            condition,
-                            isFixable(node, true),
-                            "use '.let/.also/?:/e.t.c' instead of ${condition.text}"
-                        ) {
-                            fixNullInIfCondition(node, condition, true)
-                        }
+                    KtTokens.EQEQ, KtTokens.EQEQEQ -> true
                     // `!==` and `!==` comparison can be fixed with `.let/also` operators
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt:85]: `!=` and `!==`

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt [hunk 2]
```diff
@@ -72,32 +77,59 @@ class NullChecksRule(configRules: List<RulesConfig>) : DiktatRule(
...
+                        "use '.let/.also/?:/e.t.c' instead of ${condition.text}"
+                    ) {
+                        fixNullInIfCondition(node, condition, isEqualToNull)
+                    }
+                }
             }
         }
     }
 
+    private fun isShouldBeFixed(
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt:109]:
```suggestion
    private fun shouldBeFixed(
```
or
```suggestion
    private fun isFixable(

```

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt (hunk 1 above)
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt (hunk 2 above)
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt [hunk 3]
```diff
@@ -126,6 +158,19 @@ class NullChecksRule(configRules: List<RulesConfig>) : DiktatRule(
         isEqualToNull: Boolean
     ) {
         val variableName = binaryExpression.left!!.text
+        val (thenCodeLines, elseCodeLines) = getThenAndElseLines(condition, isEqualToNull)
+        val (numberOfStatementsInElseBlock, isAssignmentInNewElseBlock) = getInfoAboutElseBlock(condition, isEqualToNull)
+
+        val elseEditedCodeLines = getEditedElseCodeLines(elseCodeLines, numberOfStatementsInElseBlock, isAssignmentInNewElseBlock)
+        val thenEditedCodeLines = getEditedThenCodeLines(variableName, thenCodeLines, elseEditedCodeLines)
+
+        val text = "$thenEditedCodeLines $elseEditedCodeLines"
```
[the remark this answers is not in the document]
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt [hunk 4]
```diff
@@ -126,6 +158,19 @@ class NullChecksRule(configRules: List<RulesConfig>) : DiktatRule(
...
+        val tree = KotlinParser().createNode(text)
```
[the remark this answers is not in the document]
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt [hunk 5]
```diff
@@ -72,32 +77,59 @@ class NullChecksRule(configRules: List<RulesConfig>) : DiktatRule(
...
+    private fun isNullOrEmptyElseBlock(elseCodeLines: List<String>?) = elseCodeLines == null || elseCodeLines.singleOrNull() == "null"
+
+    private fun isNotInsideWrongBlock(condition: ASTNode): Boolean = condition.parents().none {
+        it.elementType == CLASS_INITIALIZER ||
+                (it.elementType == CALL_EXPRESSION &&
+                        it.findChildByType(REFERENCE_EXPRESSION)?.text in listOf("run", "with", "apply"))
+    }
+
     @Suppress("UnsafeCallOnNullableType")
     private fun isFixable(condition: ASTNode,
```
[the remark this answers is not in the document]
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter4/NullChecksRule.kt]: Done. We need 2 functions, because one checks whether it is necessary to warn about null-check, and the second checks whether null-check can be auto fixed.

**Review by nulls — APPROVED** [review]

**Review by kgevorkyan — APPROVED** [review]
