### PR TITLE
Bugfix/indentation of multiline string

### LINKED ISSUE #811: Changing indentation of multiline string works incorrect
## Describe the bug

Initial code:

```kotlin
    fun `check dummy property`() {
        lintMethod(
                """
                    |// provide your check here
                """.trimMargin(),
                LintError(1, 1, ruleId, "${DUMMY_TEST_WARNING.warnText()} some detailed explanation", true)
        )
    }
```

## Expected behavior after command  `mvn diktat:fix@diktat`:
```kotlin
    fun `check dummy property`() {
        lintMethod(
            """
                |// provide your check here
            """.trimMargin(),
            LintError(1, 1, ruleId, "${DUMMY_TEST_WARNING.warnText()} some detailed explanation", true)
        )
    }
```

## Observed behavior
```kotlin
    fun `check dummy property`() {
        lintMethod(
            """
                    |// provide your check here
                """.trimMargin(),
            LintError(1, 1, ruleId, "${DUMMY_TEST_WARNING.warnText()} some detailed explanation", true)
        )
    }
```

So only first and last lines were changed.

## Environment information
* diktat version: 0.4.2
* build tool (maven/gradle): maven
* kotlin version: 1.4.31

### PR DESCRIPTION
**Pull request by Arrgentum**
## Correct margins in a multiline string template
* [ ] Correct indentation of the opening quotation mark 
* [ ] The same indentation of the opening and closing quotes

This pull request closes #811

## Actions checklist
* [ ] Correct check quotes in multiline string
* [ ] Added tests on fixers

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationRule.kt [hunk 1]
```diff
@@ -173,10 +177,30 @@ class IndentationRule(configRules: List<RulesConfig>) : DiktatRule(
         }
     }
 
+    private fun isCloseAndOpenQuoterOffset(nodeWhiteSpace: ASTNode): Boolean {
+        val nextNode = nodeWhiteSpace.treeNext
+        if (nextNode.elementType == VALUE_ARGUMENT) {
+            val nextNodeDot = if (nextNode.elementType == DOT_QUALIFIED_EXPRESSION) {
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/IndentationRule.kt:183]: nextNodeDot looks as duplicate (line 267). maybe combine?

**Review by nulls — APPROVED** [review]

**Review by 0x6675636b796f75676974687562 — APPROVED** [review]
