### PR TITLE
SAVE smoke tests should not have fixed line numbers

### LINKED ISSUE #1527: SAVE smoke tests SHOULD NOT have fixed line numbers!
Fix it asap

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* replace line numbers with placeholder Closes #1527

### CODE REVIEW

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Bug1Expected.kt [hunk 1]
```diff
@@ -1,19 +1,19 @@
-// ;warn:1:1: [FILE_NAME_MATCH_CLASS] file name is incorrect - it should match with the class described in it if there is the only one class declared: Bug1Expected.kt vs D{{.*}}
+// ;warn:$line:1: [FILE_NAME_MATCH_CLASS] file name is incorrect - it should match with the class described in it if there is the only one class declared: Bug1Expected.kt vs D{{.*}}
```
Comment (akuleshov7) [inline diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Bug1Expected.kt:1]: I remember - we were adding functionality for NO WRITING A LINE NUMBER in warning. 
Does it work?

**Review by akuleshov7 — CHANGES_REQUESTED** [review]
I think, that we should give a good example for everyone with these tests. Let's remove line numbers

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Bug1Expected.kt (hunk 1 above)
Comment (Cheshiriks) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Bug1Expected.kt:1]: We cannot completely remove here from the line number. Because Diktat does not know how to correctly define the warning line.

Comment (akuleshov7) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Bug1Expected.kt:1]: why diktat? I am saying about save

Comment (Cheshiriks) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Bug1Expected.kt:1]: Fixed all

**Review by akuleshov7 — APPROVED** [review]
