### PR TITLE
Fixed `KdocComments` for types in generic classes

### LINKED ISSUE #1825: False `KDOC_EXTRA_PROPERTY` for type in generic classes
Steps to reproduce:
```kotlin
/**
 * S3 implementation of Storage
 *
 * @param s3Operations [S3Operations] to operate with S3
 * @param K type of key
 */
abstract class AbstractReactiveStorage<K : Any>(
    s3Operations: S3Operations,
) : ReactiveStorage<K> {
  // TODO
}
```

Diktat 2.0 generates `D:/projects/save-cloud/save-cloud-common/src/jvmMain/kotlin/com/saveourtool/save/storage/AbstractReactiveStorage.kt:17:4: [KDOC_EXTRA_PROPERTY] There is property in KDoc which is not present in the class: @param K type of key (cannot be auto-corrected) (diktat-ruleset:kdoc-comments)`

### PR DESCRIPTION
**Pull request by DrAlexD**
### What's done:
- fixed case when `KDOC_EXTRA_PROPERTY` warning generation didn't take into account types in generic classes.
- added configuration `isParamTagsForGenericTypes` for `@param` tags creation for types in generic classes.
- added fixed warnings `KDOC_NO_CONSTRUCTOR_PROPERTY` for cases when configuration option are on, and then generic types must have `@param` tags in class-KDoc. Additionally added logic for replacing incorrect tag with correct one regardless of whether configuration is enabled or not.
- added new warning and fix tests.

Closes #1825

### CODE REVIEW

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt [hunk 1]
```diff
@@ -102,28 +102,34 @@ class KdocComments(configRules: List<RulesConfig>) : DiktatRule(
...
+            ?: return
 
         val parametersInKdoc = kdocBeforeClass
             .kDocTags()
             .filter { it.knownTag == KDocKnownTag.PROPERTY || it.knownTag == KDocKnownTag.PARAM }
 
-        val parametersInConstructor = node
-            .findChildrenMatching { it.elementType == VALUE_PARAMETER }
-            .mapNotNull { it.findChildByType(IDENTIFIER)?.text }
+        val parametersInTypeParameterList = typeParameterListNode
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt:117]: I guess it could be extracted into the method

**Review by nulls — APPROVED** [review]

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt (hunk 1 above)
Comment (DrAlexD) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt]: Done
