### PR TITLE
Fixed `VARIABLE_NAME_INCORRECT_FORMAT` false positive when a property has a backing field

### LINKED ISSUE #1711: `VARIABLE_NAME_INCORRECT_FORMAT` false positive when a property has a backing field
## Describe the bug

Consider this idiomatic example [taken directly](https://kotlinlang.org/docs/properties.html#backing-properties) from [https://kotlinlang.org](kotlinlang.org):

```kotlin
package com.example

class MutableTableContainer {
    private var _table: Map<String, Int>? = null

    val table: Map<String, Int>
        get() {
            if (_table == null) {
                _table = hashMapOf()
            }
            return _table ?: throw AssertionError("Set to null by another thread")
        }
}
```

Diktat **1.2.5** warns:

```
MutableTableContainer.kt:4:17: [VARIABLE_NAME_INCORRECT_FORMAT] variable name should be in lowerCamelCase and should contain only latin (ASCII) letters or numbers and should start from lower letter: _table (diktat-ruleset:identifier-naming)
```

Probably we should make an exception for backing properties whenever there's an **explicit backing field** with the corresponding name (`xyz` &rarr; `_xyz`) and of the same type.

Requirements:

 1. the **backing field** should be `private` (or have a **lower** [visibility](https://kotlinlang.org/docs/visibility-modifiers.html) than that of the **property**);
 2. the **backing field** should have a matching name (`xyz` &rarr; `_xyz`);
 3. the **backing field** should have the same type as the **property** (either convert both types to a _simple name_, or resolve to a _FQN_ before you compare; nullable subtypes should be permitted: `Map<String, Int>` &rarr; `Map<String, Int>?`);
 4. the **backing field** should have no accessors/modifiers of its own;
 5. the **property** should have at least an accessor, or a modifier, or both.

Related:

 - [ ] #1709

## Expected behavior

No warning should have been reported.

## Observed behavior

A warning was reported.

## Steps to Reproduce

Check the above code example with _Diktat_.

## Environment information
* diktat version: **1.2.5**
* build tool (maven/gradle): any
* how is diktat run (CLI, plugin, etc.): doesn't matter
* kotlin version: **1.9**
* operating system: any
* link to a project (if your project is public):

### PR DESCRIPTION
**Pull request by diphtongue**
### What's done:
- fixed warning `VARIABLE_NAME_INCORRECT_FORMAT` on `backing field`.
- added warning test.

Closes #1711

### CODE REVIEW

**Comment by nulls** [comment]
Does it close #1709 as well?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 1]
```diff
@@ -189,38 +198,55 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
                         }
                     }
                 } else if (variableName.text != "_" && !variableName.text.isLowerCamelCase()) {
+                    var isCorrectBackingField = false
+                    if (variableName.text.commonPrefixWith("_").length == 1 && variableName.text.drop(1).isLowerCamelCase()) {
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:202]: suggestion to move this new logic to a separate method, something like:
```kotlin
private fun ASTNode.isCorrectBackingField(variableName: ASTNode) {
    val propertyNodes = node.treeParent.getAllChildrenWithType(KtNodeTypes.PROPERTY)
    // bla bla
}
```

Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:202]:
```suggestion
                    val  isCorrectBackingField  = if (variableName.text.commonPrefixWith("_").length == 1 && variableName.text.drop(1).isLowerCamelCase()) {
```
and instead of `matchingNode.let { isCorrectBackingField = true }`
`return matchingNode.let { true } ?: false`

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 2]
```diff
@@ -189,38 +198,55 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
...
+                            val propertyType = propertyNode.getFirstChildWithType(TYPE_REFERENCE)
+                            propertyNode.getFirstChildWithType(IDENTIFIER)?.text == variableName.text.drop(1) &&
+                                    (propertyType?.text == nodeType?.text ||
+                                            propertyType?.getFirstChildWithType(USER_TYPE)?.text ==
+                                                    nodeType?.getFirstChildWithType(NULLABLE_TYPE)?.getFirstChildWithType(USER_TYPE)?.text) &&
+                                    node.getFirstChildWithType(MODIFIER_LIST)?.getFirstChildWithType(PRIVATE_KEYWORD) != null &&
+                                    node.getFirstChildWithType(PROPERTY_ACCESSOR) == null &&
+                                    propertyNode.getFirstChildWithType(PROPERTY_ACCESSOR) != null
+                        }
+                        matchingNode.let { isCorrectBackingField = true }
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:214]: probably you wanted to check on null here
```suggestion
                        matchingNode?.let { isCorrectBackingField = true }
```

**Review by nulls — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 3]
```diff
@@ -189,38 +198,55 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
                         }
                     }
                 } else if (variableName.text != "_" && !variableName.text.isLowerCamelCase()) {
+                    var isCorrectBackingField = false
+                    if (variableName.text.commonPrefixWith("_").length == 1 && variableName.text.drop(1).isLowerCamelCase()) {
+                        val matchingNode = propertyNodes.find { propertyNode ->
+                            val nodeType = node.getFirstChildWithType(TYPE_REFERENCE)
+                            val propertyType = propertyNode.getFirstChildWithType(TYPE_REFERENCE)
+                            propertyNode.getFirstChildWithType(IDENTIFIER)?.text == variableName.text.drop(1) &&
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:206]: maybe extract such long conditions into variables for more readability?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt (hunk 1 above)
Comment (kgevorkyan) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:202]: and please add some comments about your algorithm

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 4]
```diff
@@ -139,6 +145,34 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
...
+                val nodeType = this.getFirstChildWithType(TYPE_REFERENCE)
+                val propertyType = propertyNode.getFirstChildWithType(TYPE_REFERENCE)
+                // check that property and backing field has same type
+                val sameType = propertyType?.text == nodeType?.text
+                // check that property USER_TYPE is same as backing field NULLABLE_TYPE
+                val nodeNullableType = nodeType?.getFirstChildWithType(NULLABLE_TYPE)
+                val sameTypeWithNullable = propertyType?.getFirstChildWithType(USER_TYPE)?.text ==
+                        nodeNullableType?.getFirstChildWithType(USER_TYPE)?.text
+                val matchingNames = propertyNode.getFirstChildWithType(IDENTIFIER)?.text == variableName.text.drop(1)
+                val isPrivate = this.getFirstChildWithType(MODIFIER_LIST)?.getFirstChildWithType(PRIVATE_KEYWORD) != null
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:165]: I guess we should already have `isPrivate` method in some utils, is not it?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 5]
```diff
@@ -139,6 +145,34 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
...
+            val matchingNode = propertyNodes.find { propertyNode ->
+                val nodeType = this.getFirstChildWithType(TYPE_REFERENCE)
+                val propertyType = propertyNode.getFirstChildWithType(TYPE_REFERENCE)
+                // check that property and backing field has same type
+                val sameType = propertyType?.text == nodeType?.text
+                // check that property USER_TYPE is same as backing field NULLABLE_TYPE
+                val nodeNullableType = nodeType?.getFirstChildWithType(NULLABLE_TYPE)
+                val sameTypeWithNullable = propertyType?.getFirstChildWithType(USER_TYPE)?.text ==
+                        nodeNullableType?.getFirstChildWithType(USER_TYPE)?.text
+                val matchingNames = propertyNode.getFirstChildWithType(IDENTIFIER)?.text == variableName.text.drop(1)
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:164]: `variableName.text.drop(1)` could be extracted into variable too, since its used 2 times

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 6]
```diff
@@ -139,6 +145,34 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
...
+                val isPrivate = this.getFirstChildWithType(MODIFIER_LIST)?.getFirstChildWithType(PRIVATE_KEYWORD) != null
+
+                matchingNames && (sameType || sameTypeWithNullable) && isPrivate &&
+                        this.getFirstChildWithType(PROPERTY_ACCESSOR) == null &&
+                        propertyNode.getFirstChildWithType(PROPERTY_ACCESSOR) != null
+            }
+            return matchingNode.let { true }
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:171]:
```suggestion
            return matchingNode?.let { true } ?: false
```

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 7]
```diff
@@ -139,6 +145,34 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
         return false
     }
 
+    /**
+     * method checks that identifier is correct backing field
+     */
+    private fun ASTNode.isCorrectBackingField(variableName: ASTNode): Boolean {
+        val propertyNodes = this.treeParent.getAllChildrenWithType(KtNodeTypes.PROPERTY)
+        // check that backing field name is correct
+        if (variableName.text.commonPrefixWith("_").length == 1 && variableName.text.drop(1).isLowerCamelCase()) {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:154]: Why do you do this trick with `commonPrefixWith.length == 1` -> it should be `startsWith('_')`, no?

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt [hunk 8]
```diff
@@ -629,6 +636,33 @@ class IdentifierNamingWarnTest : LintTestBase(::IdentifierNaming) {
         lintMethod(code)
     }
 
+    @Test
+    @Tag(WarningNames.VARIABLE_NAME_INCORRECT_FORMAT)
+    fun `should not trigger on backing field`() {
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt:641]: please add more positive examples, when it is triggered on the backing field

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter6/CustomGetterSetterWarnTest.kt [hunk 9]
```diff
@@ -102,27 +102,5 @@ class CustomGetterSetterWarnTest : LintTestBase(::CustomGetterSetterRule) {
...
     }
-
-    @Test
-    @Tag(CUSTOM_GETTERS_SETTERS)
-    fun `exception for accessors or modifiers of property`() {
-        lintMethod(
-            """
-                    |package com.example
-                    |
-                    |class MutableTableContainer {
```
Comment (nulls) [inline diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter6/CustomGetterSetterWarnTest.kt]: why do you remove the test?

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt (hunk 7 above)
Comment (kgevorkyan) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:154]: guess, that `startsWith` not take into account cases like `____bla`, but `.len == 1` does

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter6/CustomGetterSetterWarnTest.kt (hunk 9 above)
Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter6/CustomGetterSetterWarnTest.kt]: Discussed offline

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt (hunk 4 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:165]: No, we haven't

File: diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt (hunk 8 above)
Comment (diphtongue) [reply diktat-rules/src/test/kotlin/com/saveourtool/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt:641]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt (hunk 7 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt]: Changed to `startsWith("_")`

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt (hunk 6 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt (hunk 5 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt (hunk 2 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt]: Done

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt (hunk 1 above)
Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt]: Done

Comment (diphtongue) [reply diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt]: Done

**Comment by diphtongue** [comment]
> Does it close #1709 as well?

No

File: diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt [hunk 10]
```diff
@@ -149,9 +185,11 @@ class IdentifierNaming(configRules: List<RulesConfig>) : DiktatRule(
         "ComplexMethod",
         "UnsafeCallOnNullableType",
     )
+
```
Comment (nulls) [inline diktat-rules/src/main/kotlin/com/saveourtool/diktat/ruleset/rules/chapter1/IdentifierNaming.kt:188]: this line is not required

**Review by nulls — APPROVED** [review]

**Review by 0x6675636b796f75676974687562 — APPROVED** [review]

**Review by kgevorkyan — APPROVED** [review]

**Review by Cheshiriks — APPROVED** [review]
